// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: languages.sql

package sqlcdb

import (
	"context"
)

const createLanguage = `-- name: CreateLanguage :one
INSERT INTO languages (
    code, name
) VALUES (
    $1, $2
)
RETURNING id, code, name
`

type CreateLanguageParams struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) CreateLanguage(ctx context.Context, arg CreateLanguageParams) (Language, error) {
	row := q.db.QueryRow(ctx, createLanguage, arg.Code, arg.Name)
	var i Language
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const getLanguage = `-- name: GetLanguage :one
SELECT id, code, name
FROM languages
WHERE id = $1
`

type GetLanguageParams struct {
	ID int32 `json:"id"`
}

func (q *Queries) GetLanguage(ctx context.Context, arg GetLanguageParams) (Language, error) {
	row := q.db.QueryRow(ctx, getLanguage, arg.ID)
	var i Language
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const getLanguageByCode = `-- name: GetLanguageByCode :one
SELECT id, code, name
FROM languages
WHERE code = $1
`

type GetLanguageByCodeParams struct {
	Code string `json:"code"`
}

func (q *Queries) GetLanguageByCode(ctx context.Context, arg GetLanguageByCodeParams) (Language, error) {
	row := q.db.QueryRow(ctx, getLanguageByCode, arg.Code)
	var i Language
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const listLanguages = `-- name: ListLanguages :many
SELECT id, code, name
FROM languages
ORDER BY name
`

func (q *Queries) ListLanguages(ctx context.Context) ([]Language, error) {
	rows, err := q.db.Query(ctx, listLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(&i.ID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
