// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Context struct {
	ID         int32       `json:"id"`
	WordID     pgtype.Int4 `json:"word_id"`
	LanguageID pgtype.Int4 `json:"language_id"`
	Context    string      `json:"context"`
}

type GrammaticalForm struct {
	ID           int32       `json:"id"`
	WordID       pgtype.Int4 `json:"word_id"`
	BaseWordID   pgtype.Int4 `json:"base_word_id"`
	GrammarType  string      `json:"grammar_type"`
	GrammarNotes pgtype.Text `json:"grammar_notes"`
}

type Group struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type GroupPermission struct {
	GroupID      int32 `json:"group_id"`
	PermissionID int32 `json:"permission_id"`
}

type Language struct {
	ID   int32  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

type LinkedAccount struct {
	ID         int32            `json:"id"`
	UserID     int32            `json:"user_id"`
	Provider   string           `json:"provider"`
	ProviderID string           `json:"provider_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Medium struct {
	ID          int32       `json:"id"`
	WordID      pgtype.Int4 `json:"word_id"`
	ContextID   pgtype.Int4 `json:"context_id"`
	MediaType   string      `json:"media_type"`
	Path        string      `json:"path"`
	Description pgtype.Text `json:"description"`
	UserID      pgtype.Int4 `json:"user_id"`
}

type Permission struct {
	ID       int32  `json:"id"`
	Codename string `json:"codename"`
	Name     string `json:"name"`
}

type Translation struct {
	ID            int32       `json:"id"`
	WordID        pgtype.Int4 `json:"word_id"`
	TranslationID pgtype.Int4 `json:"translation_id"`
}

type User struct {
	ID        int32            `json:"id"`
	Email     string           `json:"email"`
	Name      string           `json:"name"`
	Avatar    pgtype.Text      `json:"avatar"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	LastLogin pgtype.Timestamp `json:"last_login"`
	Role      string           `json:"role"`
}

type UserGroup struct {
	UserID  int32 `json:"user_id"`
	GroupID int32 `json:"group_id"`
}

type Word struct {
	ID            int32         `json:"id"`
	LanguageID    pgtype.Int4   `json:"language_id"`
	Word          string        `json:"word"`
	BaseFormID    pgtype.Int4   `json:"base_form_id"`
	Pronunciation pgtype.Text   `json:"pronunciation"`
	Category      pgtype.Text   `json:"category"`
	Level         pgtype.Text   `json:"level"`
	Popularity    pgtype.Float8 `json:"popularity"`
}
