// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcdb

import (
	"context"
)

type Querier interface {
	AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error
	AssignPermissionToGroup(ctx context.Context, arg AssignPermissionToGroupParams) error
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateLanguage(ctx context.Context, arg CreateLanguageParams) (Language, error)
	CreateLinkedAccount(ctx context.Context, arg CreateLinkedAccountParams) (LinkedAccount, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	// USERS & LINKED ACCOUNTS --
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWord(ctx context.Context, arg CreateWordParams) (CreateWordRow, error)
	DeleteWord(ctx context.Context, arg DeleteWordParams) error
	GetGroupPermissions(ctx context.Context, arg GetGroupPermissionsParams) ([]Permission, error)
	GetLanguage(ctx context.Context, arg GetLanguageParams) (Language, error)
	GetLanguageByCode(ctx context.Context, arg GetLanguageByCodeParams) (Language, error)
	GetLinkedAccount(ctx context.Context, arg GetLinkedAccountParams) (LinkedAccount, error)
	GetLinkedAccountsByEmail(ctx context.Context, arg GetLinkedAccountsByEmailParams) ([]LinkedAccount, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByProviderID(ctx context.Context, arg GetUserByProviderIDParams) (GetUserByProviderIDRow, error)
	// GROUPS, PERMISSIONS & RELATIONSHIPS --
	GetUserGroups(ctx context.Context, arg GetUserGroupsParams) ([]Group, error)
	GetUserPermissions(ctx context.Context, arg GetUserPermissionsParams) ([]Permission, error)
	GetWord(ctx context.Context, arg GetWordParams) (GetWordRow, error)
	ListLanguages(ctx context.Context) ([]Language, error)
	ListWords(ctx context.Context, arg ListWordsParams) ([]ListWordsRow, error)
	UpdateUserLogin(ctx context.Context, arg UpdateUserLoginParams) error
	UpdateWord(ctx context.Context, arg UpdateWordParams) (UpdateWordRow, error)
}

var _ Querier = (*Queries)(nil)
