// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToGroup = `-- name: AddUserToGroup :exec
INSERT INTO user_groups (user_id, group_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddUserToGroupParams struct {
	UserID  int32 `json:"user_id"`
	GroupID int32 `json:"group_id"`
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error {
	_, err := q.db.Exec(ctx, addUserToGroup, arg.UserID, arg.GroupID)
	return err
}

const assignPermissionToGroup = `-- name: AssignPermissionToGroup :exec
INSERT INTO group_permissions (group_id, permission_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignPermissionToGroupParams struct {
	GroupID      int32 `json:"group_id"`
	PermissionID int32 `json:"permission_id"`
}

func (q *Queries) AssignPermissionToGroup(ctx context.Context, arg AssignPermissionToGroupParams) error {
	_, err := q.db.Exec(ctx, assignPermissionToGroup, arg.GroupID, arg.PermissionID)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name)
VALUES ($1)
RETURNING id, name
`

type CreateGroupParams struct {
	Name string `json:"name"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.Name)
	var i Group
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createLinkedAccount = `-- name: CreateLinkedAccount :one
INSERT INTO linked_accounts (user_id, provider, provider_id)
VALUES ($1, $2, $3)
RETURNING id, user_id, provider, provider_id, created_at
`

type CreateLinkedAccountParams struct {
	UserID     int32  `json:"user_id"`
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) CreateLinkedAccount(ctx context.Context, arg CreateLinkedAccountParams) (LinkedAccount, error) {
	row := q.db.QueryRow(ctx, createLinkedAccount, arg.UserID, arg.Provider, arg.ProviderID)
	var i LinkedAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
	)
	return i, err
}

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (codename, name)
VALUES ($1, $2)
RETURNING id, codename, name
`

type CreatePermissionParams struct {
	Codename string `json:"codename"`
	Name     string `json:"name"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission, arg.Codename, arg.Name)
	var i Permission
	err := row.Scan(&i.ID, &i.Codename, &i.Name)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, name, avatar, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, avatar, created_at, last_login, role
`

type CreateUserParams struct {
	Email  string      `json:"email"`
	Name   string      `json:"name"`
	Avatar pgtype.Text `json:"avatar"`
	Role   string      `json:"role"`
}

// USERS & LINKED ACCOUNTS --
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.Avatar,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Avatar,
		&i.CreatedAt,
		&i.LastLogin,
		&i.Role,
	)
	return i, err
}

const getGroupPermissions = `-- name: GetGroupPermissions :many
SELECT p.id, p.codename, p.name
FROM permissions p
JOIN group_permissions gp ON p.id = gp.permission_id
WHERE gp.group_id = $1
`

type GetGroupPermissionsParams struct {
	GroupID int32 `json:"group_id"`
}

func (q *Queries) GetGroupPermissions(ctx context.Context, arg GetGroupPermissionsParams) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getGroupPermissions, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Codename, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkedAccount = `-- name: GetLinkedAccount :one
SELECT id, user_id, provider, provider_id, created_at FROM linked_accounts WHERE provider = $1 AND provider_id = $2
`

type GetLinkedAccountParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) GetLinkedAccount(ctx context.Context, arg GetLinkedAccountParams) (LinkedAccount, error) {
	row := q.db.QueryRow(ctx, getLinkedAccount, arg.Provider, arg.ProviderID)
	var i LinkedAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkedAccountsByEmail = `-- name: GetLinkedAccountsByEmail :many
SELECT la.id, la.user_id, la.provider, la.provider_id, la.created_at
FROM linked_accounts la
JOIN users u ON u.id = la.user_id
WHERE u.email = $1
`

type GetLinkedAccountsByEmailParams struct {
	Email string `json:"email"`
}

func (q *Queries) GetLinkedAccountsByEmail(ctx context.Context, arg GetLinkedAccountsByEmailParams) ([]LinkedAccount, error) {
	rows, err := q.db.Query(ctx, getLinkedAccountsByEmail, arg.Email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkedAccount
	for rows.Next() {
		var i LinkedAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, avatar, created_at, last_login, role FROM users WHERE email = $1
`

type GetUserByEmailParams struct {
	Email string `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Avatar,
		&i.CreatedAt,
		&i.LastLogin,
		&i.Role,
	)
	return i, err
}

const getUserByProviderID = `-- name: GetUserByProviderID :one
SELECT u.id, email, name, avatar, u.created_at, last_login, role, la.id, user_id, provider, provider_id, la.created_at FROM users u
JOIN linked_accounts la ON u.id = la.user_id
WHERE la.provider = $1 AND la.provider_id = $2
`

type GetUserByProviderIDParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

type GetUserByProviderIDRow struct {
	ID          int32            `json:"id"`
	Email       string           `json:"email"`
	Name        string           `json:"name"`
	Avatar      pgtype.Text      `json:"avatar"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	LastLogin   pgtype.Timestamp `json:"last_login"`
	Role        string           `json:"role"`
	ID_2        int32            `json:"id_2"`
	UserID      int32            `json:"user_id"`
	Provider    string           `json:"provider"`
	ProviderID  string           `json:"provider_id"`
	CreatedAt_2 pgtype.Timestamp `json:"created_at_2"`
}

func (q *Queries) GetUserByProviderID(ctx context.Context, arg GetUserByProviderIDParams) (GetUserByProviderIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByProviderID, arg.Provider, arg.ProviderID)
	var i GetUserByProviderIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Avatar,
		&i.CreatedAt,
		&i.LastLogin,
		&i.Role,
		&i.ID_2,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt_2,
	)
	return i, err
}

const getUserGroups = `-- name: GetUserGroups :many

SELECT g.id, g.name
FROM groups g
JOIN user_groups ug ON g.id = ug.group_id
WHERE ug.user_id = $1
`

type GetUserGroupsParams struct {
	UserID int32 `json:"user_id"`
}

// GROUPS, PERMISSIONS & RELATIONSHIPS --
func (q *Queries) GetUserGroups(ctx context.Context, arg GetUserGroupsParams) ([]Group, error) {
	rows, err := q.db.Query(ctx, getUserGroups, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT DISTINCT p.id, p.codename, p.name
FROM permissions p
JOIN group_permissions gp ON p.id = gp.permission_id
JOIN user_groups ug ON ug.group_id = gp.group_id
WHERE ug.user_id = $1
`

type GetUserPermissionsParams struct {
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetUserPermissions(ctx context.Context, arg GetUserPermissionsParams) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Codename, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserLogin = `-- name: UpdateUserLogin :exec
UPDATE users
SET last_login = $1
WHERE email = $2
`

type UpdateUserLoginParams struct {
	LastLogin pgtype.Timestamp `json:"last_login"`
	Email     string           `json:"email"`
}

func (q *Queries) UpdateUserLogin(ctx context.Context, arg UpdateUserLoginParams) error {
	_, err := q.db.Exec(ctx, updateUserLogin, arg.LastLogin, arg.Email)
	return err
}
