// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: words.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWord = `-- name: CreateWord :one
INSERT INTO words (
    language_id, 
    word, 
    pronunciation, 
    category, 
    level, 
    popularity
) VALUES (
    (SELECT id FROM languages WHERE code = $1),
    $2, $3, $4, $5, $6
)
RETURNING id, word, pronunciation, category, level, popularity
`

type CreateWordParams struct {
	Code          string        `json:"code"`
	Word          string        `json:"word"`
	Pronunciation pgtype.Text   `json:"pronunciation"`
	Category      pgtype.Text   `json:"category"`
	Level         pgtype.Text   `json:"level"`
	Popularity    pgtype.Float8 `json:"popularity"`
}

type CreateWordRow struct {
	ID            int32         `json:"id"`
	Word          string        `json:"word"`
	Pronunciation pgtype.Text   `json:"pronunciation"`
	Category      pgtype.Text   `json:"category"`
	Level         pgtype.Text   `json:"level"`
	Popularity    pgtype.Float8 `json:"popularity"`
}

func (q *Queries) CreateWord(ctx context.Context, arg CreateWordParams) (CreateWordRow, error) {
	row := q.db.QueryRow(ctx, createWord,
		arg.Code,
		arg.Word,
		arg.Pronunciation,
		arg.Category,
		arg.Level,
		arg.Popularity,
	)
	var i CreateWordRow
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Pronunciation,
		&i.Category,
		&i.Level,
		&i.Popularity,
	)
	return i, err
}

const deleteWord = `-- name: DeleteWord :exec
DELETE FROM words
WHERE id = $1
`

type DeleteWordParams struct {
	ID int32 `json:"id"`
}

func (q *Queries) DeleteWord(ctx context.Context, arg DeleteWordParams) error {
	_, err := q.db.Exec(ctx, deleteWord, arg.ID)
	return err
}

const getWord = `-- name: GetWord :one
SELECT w.id, w.word, l.name AS language, w.pronunciation, w.category, w.level, w.popularity
FROM words w
JOIN languages l ON w.language_id = l.id
WHERE w.id = $1
`

type GetWordParams struct {
	ID int32 `json:"id"`
}

type GetWordRow struct {
	ID            int32         `json:"id"`
	Word          string        `json:"word"`
	Language      string        `json:"language"`
	Pronunciation pgtype.Text   `json:"pronunciation"`
	Category      pgtype.Text   `json:"category"`
	Level         pgtype.Text   `json:"level"`
	Popularity    pgtype.Float8 `json:"popularity"`
}

func (q *Queries) GetWord(ctx context.Context, arg GetWordParams) (GetWordRow, error) {
	row := q.db.QueryRow(ctx, getWord, arg.ID)
	var i GetWordRow
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Language,
		&i.Pronunciation,
		&i.Category,
		&i.Level,
		&i.Popularity,
	)
	return i, err
}

const listWords = `-- name: ListWords :many
SELECT w.id, w.word, l.name AS language, w.pronunciation, w.category, w.level, w.popularity
FROM words w
JOIN languages l ON w.language_id = l.id
ORDER BY w.id
LIMIT $1 OFFSET $2
`

type ListWordsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListWordsRow struct {
	ID            int32         `json:"id"`
	Word          string        `json:"word"`
	Language      string        `json:"language"`
	Pronunciation pgtype.Text   `json:"pronunciation"`
	Category      pgtype.Text   `json:"category"`
	Level         pgtype.Text   `json:"level"`
	Popularity    pgtype.Float8 `json:"popularity"`
}

func (q *Queries) ListWords(ctx context.Context, arg ListWordsParams) ([]ListWordsRow, error) {
	rows, err := q.db.Query(ctx, listWords, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWordsRow
	for rows.Next() {
		var i ListWordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Word,
			&i.Language,
			&i.Pronunciation,
			&i.Category,
			&i.Level,
			&i.Popularity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWord = `-- name: UpdateWord :one
UPDATE words
SET 
    word = $2,
    pronunciation = $3,
    category = $4,
    level = $5,
    popularity = $6
WHERE id = $1
RETURNING id, word, pronunciation, category, level, popularity
`

type UpdateWordParams struct {
	ID            int32         `json:"id"`
	Word          string        `json:"word"`
	Pronunciation pgtype.Text   `json:"pronunciation"`
	Category      pgtype.Text   `json:"category"`
	Level         pgtype.Text   `json:"level"`
	Popularity    pgtype.Float8 `json:"popularity"`
}

type UpdateWordRow struct {
	ID            int32         `json:"id"`
	Word          string        `json:"word"`
	Pronunciation pgtype.Text   `json:"pronunciation"`
	Category      pgtype.Text   `json:"category"`
	Level         pgtype.Text   `json:"level"`
	Popularity    pgtype.Float8 `json:"popularity"`
}

func (q *Queries) UpdateWord(ctx context.Context, arg UpdateWordParams) (UpdateWordRow, error) {
	row := q.db.QueryRow(ctx, updateWord,
		arg.ID,
		arg.Word,
		arg.Pronunciation,
		arg.Category,
		arg.Level,
		arg.Popularity,
	)
	var i UpdateWordRow
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Pronunciation,
		&i.Category,
		&i.Level,
		&i.Popularity,
	)
	return i, err
}
