FROM golang:1.24 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags netgo -o backend ./cmd/server/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/backend .
COPY --from=builder /app/internal/db/migrations /app/internal/db/migrations
COPY --from=builder /app/locales /app/locales
CMD ["./backend"]